### ISSUE TITLE
Installation fails with composer 

### ISSUE THREAD

**Issue by robjensen82** [backbee/BackBee#145]
```
{
    "require": {
        "backbee/backbee": "@stable"
    }
}
```
Resulted in 
```
composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package backbee/backbee could not be found in any version, there may be a typo in the package name.
```

**Comment by robjensen82** [comment]
Hey @eric-chau,

I gave that a go and this was the output.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for backbee/backbee dev-master -> satisfiable by backbee/backbee[dev-master].
    - backbee/backbee dev-master requires respect/validation 0.7.*@dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by mickaelandrieu** [comment]
Hi @robjensen82 ,

this is probably because 0.7.*@dev branch no longer exists in ``respect/validation`` project.

I will fix this today, but you can already install backbee by edit the version of ``respect/validation`` with ``0.6.1``, [the latest stable](https://packagist.org/packages/respect/validation).

Again, thank you for report :)

**Comment by AhrimanSefid** [comment]
Plz help in install.

C:\wamp\www\ba>composer require "backbee/backbee=dev-master"
./composer.json has been updated
Loading composer repositories with package information

  [RuntimeException]
  Failed to clone http://gitlab.lp-digital.fr/backbuilder.git, git was not fo
  und, check that it is installed and in your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update]
[--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-
packages] [packages1] ... [packagesN]

C:\wamp\www\ba>

**Comment by AhrimanSefid** [comment]
C:\wamp\www\ba>composer install
Loading composer repositories with package information

  [RuntimeException]
  Failed to clone http://gitlab.lp-digital.fr/backbuilder.git, git was not fo
  und, check that it is installed and in your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-p
lugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress
] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [pac
kages1] ... [packagesN]

C:\wamp\www\ba>

**Comment by mickaelandrieu** [comment]
"'git' is not recognized as an internal or external command,
operable program or batch file." => you need to install git before

**Comment by AhrimanSefid** [comment]
not work plz help in fixed.

**Comment by ndufreche** [comment]
@AhrimanSefid try the checked answer on this [stackoverflow post](http://stackoverflow.com/questions/20169348/error-git-was-not-found-installing-laravel-with-composer-windows)
It's a Window solution.
