### ISSUE TITLE
[Config] change security.yml dependency to bb5_secret_key parameter

### ISSUE THREAD

**Issue by eric-chau** [backbee/BackBee#172]
``Config/security.yml`` has dependency to ``bb5_secret_key`` from BackBee service container. We should change it to ``secret_key`` instead of ``bb5_secret_key``.

**Comment by mickaelandrieu** [comment]
this issue concerns 0.1x.* branch or master branch ?

**Comment by eric-chau** [comment]
``master branch`` mainly, cause we have to remove every reference to bb5 (BackBuilder5) which is the wrong project name.
