### ISSUE TITLE
[Rest] change get classcontent category route pattern

### ISSUE THREAD

**Issue by eric-chau** [backbee/BackBee#176]
Current classcontent category route pattern is: ``/rest/{version}/classcontent/category/{id}``

It means that you cannot access to classcontent that has __category__ as classname. My proposal is to rename classcontent category route pattern to: ``/rest/{version}/classcontent-category/{id}``

What do you think about it @fkroockmann and @hbaptiste? I ping you both cause you implemented it in your applications.

**Comment by fkroockmann** [comment]
I suggest this pattern: ``/rest/{version}/classcontent?category={id}``.
You list all content with category 'id'.

With this pattern: ``/rest/{version}/classcontent-category/{id}``, i don't understand what data is returned.

**Comment by eric-chau** [comment]
@fkroockmann, I think you misunderstand Restful API concepts cause a given URL pattern allow you to access to one resource. By doing ``/rest/{version}/classcontent?category={id}`` you mean that with one URL pattern (which is ``/rest/{version}/classcontent``) you can get classcontent resource or classcontent's category resource, which is really confusing.

Also, we already have ``definition``, ``concise`` and ``info`` filter which all of them return classcontent resource but in different format. Atleast this is my opinion, don't know if @ndufreche, @crouillon and @mickaelandrieu agree with me.

**Comment by fkroockmann** [comment]
For me category is an filter and this pattern ``/rest/{version}/classcontent-category/{id}`` is so confuse.

**Comment by eric-chau** [comment]
What is confuse to you? classcontent and classcontent's category are two differents resources so that must imply two differents pattern to access to each other.

**Comment by fkroockmann** [comment]
I'm lost :o, if i want all classcontent by one category, how i request this ? and if i want all categories, how i request this ?

**Comment by ndufreche** [comment]
@eric-chau it's actually exist a classcontent-category class or is just a category of classcontent yml  ?

**Comment by eric-chau** [comment]
Well, first i will clarify some concepts in BackBee. You have ``ClassContent`` which is a notion you're confortable with i think and in the other hand you have ``ClassContent\Category`` which is completely different from ``ClassContent``.

If we follow your suggestion (``/rest/{version}/classcontent?category={id}``) we will end with an API service that can return classcontent or classcontent's category. This is really bad and confusing, isn't it?

If you want to get every classcontent of a given category (let's say media), you keep performing the same request as actual (``/rest/{version}/classcontent?category=media``), cause your goal is to retrieve classcontent.

If you want to get every category you have to perform Rest request to this URL ``/rest/{version}/classcontent-category``.

Let me know if it appears obvious for you or not.

**Comment by ndufreche** [comment]
In basing me on the YML, for me we have to call the ClassContent Categories by this url :
/rest/{version}/classcontent-properties-category

**Comment by eric-chau** [comment]
@ndufreche, we don't have to do it anymore since we have ``ClassContent\Category`` and it's this resource we want to access, so ``/rest/{version}/classcontent-category`` is enough.

**Comment by ndufreche** [comment]
I'm totally agree with you @eric-chau, but the matter is that ClassContent Categroy notion don't really exist in BackBee. If he actually exist, is uniquely for the toolbar and is just totally an optional notion.

Block work without categories and is for that of category is in properties sections.

And so, I don't think that two url are REST valid.

**Comment by eric-chau** [comment]
@ndufreche, the thing is that now ``ClassContent\Category`` is real in BackBee master, we have a ``ClassContent\CategoryManager`` too. Previous version of BackBee didn't allow you to work with classcontent's category but now it's possible. We reworked it with @crouillon.
Plus you're right with the fact that currently we need this service for our frontend (ToolbarBundle and BBCoreJs), but this is also true that if anyone else who want to develops its own frontend will need to get classcontent category too. It's a real and useful notion. Atleast this is what I believe. That also why I pinged @crouillon so he can tell me if i'm wrong.

**Comment by ndufreche** [comment]
O.o I didn't know that. If we have a real class, is different and I'm totally agree with @fkroockmann proposal.

filter ClassContent by categroy :
/rest/{version}/classcontent?category=something

If i wont all categories :
/rest/{version}/classcontent/category

**Comment by eric-chau** [comment]
I think we really misunderstand each other. My proposal is that to get every classcontent category we use this route: ``/rest/{version}/classcontent-category``. If we do so, we can have a classcontent with classname equals to ``category``. In current design we cannot access to classcontent with classname equals to ``category``.

I still say what i said earlier, to get classcontent by category, route still being the same: ``/rest/{version}/classcontent?category=something``

I really think that english don't help us at all. We are saying the same thing from the start and seems i can't explain my proposal properly. Apologize.

**Comment by eric-chau** [comment]
Resolved in PR #182
