### ISSUE TITLE
Remove old backbee toolbar source files

### ISSUE THREAD

**Issue by eric-chau** [backbee/BackBee#179]
It includes Php, Javascript and CSS files.

New BackBee\ToolbarBundle will embed its own source files.

**Comment by mickaelandrieu** [comment]
What is the version(s) of BackBee concerned by this issue ?

**Comment by eric-chau** [comment]
BackBee master (min version 0.12)

**Comment by mickaelandrieu** [comment]
@eric-chau is this issue solved ?
