### ISSUE TITLE
[Rest] add support to batch Rest API call

### ISSUE THREAD

**Issue by eric-chau** [backbee/BackBee#189]
REST API is designed to handle one resource per call. But oftenly we need to perform action on multiple resources, for example:

- update of multiples contents
- update of multiples pages' status

The idea is to add a flag into request's header that activate handler of batch request.

**Comment by mickaelandrieu** [comment]
oh gosh dont say RESTful :D => https://speakerdeck.com/willdurand/rest-dans-le-monde-symfony-phptour

**Comment by eric-chau** [comment]
Who said it? :o

**Comment by eric-chau** [comment]
This is not possible to create a generic controller and keep handling correctly annotation so we give up this feature. We will do it specifically case by case.
