### ISSUE TITLE
Rename IApplication to ApplicationInterface

### ISSUE THREAD

**Issue by eric-chau** [backbee/BackBee#201]
Don't forget to update every class that implements this interface.

**Comment by mickaelandrieu** [comment]
Can I work on it ?

**Comment by eric-chau** [comment]
If you want, I don't mind =) Just be sure that @crouillon agrees with it.

**Comment by mickaelandrieu** [comment]
ok, let's wait for @crouillon agreement :)

**Comment by crouillon** [comment]
I agree with you ;-)
