### ISSUE TITLE
[FrontController] dispatch event on controller post call

### ISSUE THREAD

**Issue by eric-chau** [backbee/BackBee#221]
Currently with the JsonRPC, two events are dispatched at two keys moments:

- ``services.local.contentblocks.precall`` is dispatched before the call of the controller's action
- ``services.local.contentblocks.postcall`` is dispatched after the call of the controller's action

Since JsonRPC is gonna be remove from BackBee and replaced by Rest, we have to provide similar behavior but not only for Rest request, it has to be done for every request handled by BackBee. Also, there is several issue about event's name dispatched by ``BackBee\FrontController\FrontController``:

In ``::invokeAction``, line 562:
````php
$eventName = str_replace('\\', '.', strtolower(get_class($controller[0])));
if (0 === strpos($eventName, 'BackBee.')) {
    $eventName = substr($eventName, 12);
}
```

In ``::invokeAction``, line 571:
````php
$eventName .= '.pre'.$this->getRequest()->attributes->get('_action');
$this->dispatch($eventName.'.pre'.$this->getRequest()->attributes->get('_action'));
```

**Comment by mickaelandrieu** [comment]
and how about native [Symfony event](https://github.com/symfony/HttpKernel/tree/master/Event) for before and after controller action ?

**Comment by eric-chau** [comment]
I had taken a look at this but I don't think this suit our needs.

**Comment by mickaelandrieu** [comment]
Yup, take a look to [HttpKernel->handleRaw()](https://github.com/symfony/HttpKernel/blob/master/HttpKernel.php#L139), we can probably catch core events ;)

**Comment by eric-chau** [comment]
The thing is that we implements ``Symfony\Component\HttpKernel\HttpKernelInterface`` and not extending ``Symfony\Component\HttpKernel\HttpKernel``. Take a look at my PR #222 I created two new events called ``PreRequestEvent`` and ``PostResponseEvent``. I already talk about it to @crouillon and we agree about this way to do. Let me know if you think something is wrongly done in my PR. Thanks.
