### ISSUE TITLE
[rest] Complete rest user controller

### ISSUE THREAD

**Issue by ndufreche** [backbee/BackBee#225]
New update :
- [ ] A User have to return the groups they are part
- [ ] Update getCollectionAction with adding filters
  - [ ] Group filter
- [ ] Develop patchAction
  - [ ] Patch user group

**Comment by ndufreche** [comment]
The user controller still in development.

**Comment by mickaelandrieu** [comment]
what is the status of this issue ?

**Comment by eric-chau** [comment]
@ndufreche can we close this issue?

**Comment by ndufreche** [comment]
Yes :)

**Comment by eric-chau** [comment]
Thank you =)
