### ISSUE TITLE
[REST] [Page] missing data

### ISSUE THREAD

**Issue by fkroockmann** [backbee/BackBee#228]
On a getAction, the modified and created data are not retrieved

**Comment by mickaelandrieu** [comment]
Hi @fkroockmann, can you create a minimal test which won't pass because the actual behavior is not what we expect ?

**Comment by mickaelandrieu** [comment]
@fkroockmann can you confirm bug ?

**Comment by eric-chau** [comment]
This is not a bug but I confirm that the created and modified data are missing.
