### ISSUE TITLE
[ClassContent] Rename every classcontent's name to respect PascalCase

### ISSUE THREAD

**Issue by eric-chau** [backbee/BackBee#230]
To avoid php classname like ``BackBee\ClassContent\Element\text`` or ``BackBee\ClassContent\Element\image``.

**Comment by mickaelandrieu** [comment]
PascalCase ?

**Comment by eric-chau** [comment]
PascalCase distinguished from CamelCase by the restriction that the first letter must be upper case. ("camelCase" isn't PascalCase, but "PascalCase" is.)
