### ISSUE TITLE
Problème d'encodage d'un caractère sur le sélecteur du contenu

### ISSUE THREAD

**Issue by mickaelandrieu** [backbee/BackBee#25]

**Comment by eric-chau** [comment]
We need more detail to resolve it. Also can we check if it is still the case on ``master`` branch?

**Comment by mickaelandrieu** [comment]
this is an issue from the old redmine, the perfect proof that we need *explicit* description for an issue :)

to be closed ?

**Comment by eric-chau** [comment]
This issue seems outdated.
