### ISSUE TITLE
REST Api Extension 

### ISSUE THREAD

**Issue by azamouchi** [backbee/BackBee#254]
Hi, 
i am trying to create a REST API of a BackBee based website. 
In the database generated by the CMS, there is the "page" table in which i can find all sort of created content, but i can't locate the table in which the content of the page is stored, for example (i can get all the titles of the articles published on the website from the "page" table, but i can't find the related article subtitle, text, image .. etc). where can i find this data ?

currently i am using a php framework to create the REST Api, but i would like to know if there is any extension for BackBee that can help me to easily achieve my task ?

Thank you

**Comment by ndufreche** [comment]
Hello @azamouchi.

We are actually actively working on the Transition between the old RPC server (BackBee 0.11) to REST API (BackBee master).
But you can't switch from 0.11 to master for now, the new administration (based on the new REST API) is not ready yet and the RPC is totally drop from the BackBee sources.
If you want to build your own REST API I suggest you, to take a look at the REST component in the master branch to see how we implemented it. But there isn't documentation yet.
The REST API is based on JMS/Serializer to serialize BackBee contents and all the system controller/route/action it's based on Symfony Controller system.

If you have more question, you can tell us here or on the [BackBee Gitter](https://gitter.im/backbee/BackBee).

**Comment by azamouchi** [comment]
Ok, thank's for your help. i'll see what i can do

**Comment by eric-chau** [comment]
Hey @azamouchi, is this issue still up-to-date? Did you need any help?

**Comment by eric-chau** [comment]
This issue seems over, I close it.
