### ISSUE TITLE
[Error] Get errors in good rendring mode

### ISSUE THREAD

**Issue by ndufreche** [backbee/BackBee#255]
In REST mode, we need JSON errors, to easily debugging, Actually we need to watch the error has HTML in the console and this not very useful and we can't understand the error in Javascript because is not the good data mode waiting.

**Comment by mickaelandrieu** [comment]
Hi,

after investigation, I cant' because Ajax calls from BbCoreJS don't ask for json, you need to add 
un Accept "application/json" I may treat on PHP side to send you back a "Error" JsonResponse object.

**Comment by ndufreche** [comment]
We can update our REST client to ask JSON, if it can fix the response in JSON style.

I create an issue BbCoreJs for that.

Thanks @mickaelandrieu

**Comment by ndufreche** [comment]
done backbee/BbCoreJs#273

**Comment by mickaelandrieu** [comment]
@ndufreche ping me when it's done, from "my side", I only need to check the request accept header and return a Json Response (specific to BackBee) ?

Tell me more about your needs, I can improve the formatted response ;)

**Comment by ndufreche** [comment]
I have do the link behind the to issues, but i will add a ping too.

**Comment by eric-chau** [comment]
I close this issue, tell me if I'm wrong but it is already resolved.
