### ISSUE TITLE
fix Error on autoloading class BackBuilder\Validator\Rules\Image

### ISSUE THREAD

**Issue by crouillon** [backbee/BackBee#265]

**Comment by crouillon** [comment]
Try to redeclare class Respect\Validation\Rules\Image in C:\Data\www\BFM\BackBuilder\Validator\Rul
es\Image.php

**Comment by mickaelandrieu** [comment]
already fixed in master branch ;)

**Comment by crouillon** [comment]
Yes i saw it ;-) thx
