### ISSUE TITLE
Apply the coding styles of Symfony

### ISSUE THREAD

**Issue by mickaelandrieu** [backbee/BackBee#295]
http://symfony.com/doc/current/contributing/code/standards.html

* Interfaces should be suffixed by Interface
* abstract classes should be prefixed by Abstract
* Exception classes should be suffixed by Exception

**Comment by nicolas-bastien** [comment]
@mickaelandrieu want some help on this ?

**Comment by mickaelandrieu** [comment]
@nicolas-bastien yes, maybe a tool can make that for us, what do you think ?

**Comment by mickaelandrieu** [comment]
done.
