### ISSUE TITLE
[QA] class naming 

### ISSUE THREAD

**Issue by nicolas-bastien** [backbee/BackBee#298]
- ThemesManager and AbstractThemesManager should be named ThemeManager and AbstractThemeManager (maybe there is other like this but this is the only one I found so far)

- Class alias should be camelCase too
ex RouteCollection 

use Symfony\Component\Routing\RouteCollection as sfRouteCollection;
should be
use Symfony\Component\Routing\RouteCollection as SymfonyRouteCollection;

**Comment by mickaelandrieu** [comment]
totaly agree :+1:

**Comment by mickaelandrieu** [comment]
done.

**Comment by nicolas-bastien** [comment]
@mickaelandrieu if you want take advantage of github you should link your commit to your issue

with this one add #298 in your commit and you'll be able to see it in github interface, really usefull for history ;-)
