### ISSUE TITLE
Default classcontent is not savable

### ISSUE THREAD

**Issue by fkroockmann** [backbee/BackBee#324]
When you create a page with a template having a default content, the content has a "new" status and therefore is not displayed in " not connected" mod . It is also impossible to commit.

**Comment by fkroockmann** [comment]
@mickaelandrieu can you resolve this plz ? :)

**Comment by eric-chau** [comment]
@fkroockmann, this is caused by the fact that a default content created by page and its layout is not linked to any draft. And the classcontent REST API only returns contents that have draft for the current user. It won't be that easy to fix it properly.
