### ISSUE TITLE
Install does'nt work with debug false

### ISSUE THREAD

**Issue by fkroockmann** [backbee/BackBee#329]
With debug false, the installtion does'nt work and throw an error: 
![bug](https://cloud.githubusercontent.com/assets/9247945/7372869/771d5cbc-edc9-11e4-96f8-f9429b22a851.png)

I suppose the container is not build correctly.

**Comment by eric-chau** [comment]
I did some tests but none of them were relevant. By comparing a working container dump to the supposed invalid container dump, the only difference is the filename (and so the classname too).

**Comment by eric-chau** [comment]
A PR is currently under review to fix this issue: [backbee/backbee-standard: issue 140](https://github.com/backbee/backbee-standard/pull/140)

**Comment by eric-chau** [comment]
Fixed in ``backbee/backbee-standard``.
