### ISSUE TITLE
Check rights on REST controllers in BackBee

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BackBee#363]
A description is supposed to help developpers to actualy understand why et how he can resolve the issue.

For example, list all concerned controllers:

- [x] AclController
- [x] BundleController (https://github.com/backbee/BackBee/issues/365)
- [x] ClassContentController (https://github.com/backbee/BackBee/pull/368)
- [x] GroupController (https://github.com/backbee/BackBee/issues/364)
- [x] LayoutController (https://github.com/backbee/BackBee/pull/371)
- [x] MediaController (https://github.com/backbee/BackBee/pull/389)
- [x] MediaFolderController (https://github.com/backbee/BackBee/pull/397)
- [x] PageController
- [x] ResourceController (https://github.com/backbee/BackBee/pull/395)
- [x] SecurityController (https://github.com/backbee/BackBee/pull/392)
- [x] SiteController
- [x] UserController

**Comment by mickaelandrieu** [comment]
@clementbonfils #389 is locked, we need @crouillon.
