### ISSUE TITLE
Remove unused components from project

### ISSUE THREAD

**Issue by eric-chau** [backbee/BackBee#376]
- ``Application``
- ``Form``
- unused classes from ``Security`` component
- unused classes from ``Bundle`` component

**Comment by eric-chau** [comment]
I'm on it

**Comment by mickaelandrieu** [comment]
``Importer`` also ?

You can move it outside BackBee core, inside backbee/importer repository maybe ?

**Comment by eric-chau** [comment]
Yeah sure, but i will do separated ticket for these specific task.

**Comment by eric-chau** [comment]
Resolved.
