### ISSUE TITLE
PHP Deprecated in Backbee\Utils\String

### ISSUE THREAD

**Issue by fkroockmann** [backbee/BackBee#449]
When i do install, i have:

PHP Deprecated:  BackBee\Utils\String uses a reserved class name (String) that will break on PHP 7 and higher in /home/florian/projects/backbee-standard-js/vendor/symfony/debug/DebugClassLoader.php on line 182

**Comment by fkroockmann** [comment]
ping @mickaelandrieu

**Comment by mickaelandrieu** [comment]
I know, this need a refactoring on BackBee core side to use StringUtils instead of String class which will be marked as deprecated.

I need time to push 1.1 of backbee/utils.

**Comment by mickaelandrieu** [comment]
Fixed. We need to update backbee/utils to 2.0 when this pull request (https://github.com/backbee/utils/pull/4) will be reviewed, validated and merged.
