### ISSUE TITLE
install backbee without composer

### ISSUE THREAD

**Issue by tschallacka** [backbee/BackBee#476]
Okay. this annoys the living daylight out of me.

I'm trying to install backbee but composer won't install on my windows 2008 server with IIS because it keeps looking into the wrong php directory for its stuff and there is no way to change it without breaking all other sites.

Please provide a download package or installation setup that does not require composer. Just click and drag and it should have everything in there. Not forcing me to debug and trouble shoot composer for this one single install.

If it were linux i'd have no issues. but windows is horrible but i'm tied ot the platform from higher up, but the installation process is needlessly infuriating(yea, try finding mcrypt for php 5.5... its not in the default downloads..

**Comment by mickaelandrieu** [comment]
Hi @tschallacka, for now we don't plan to support "officialy" windows server 2008.

We will provide a downloadable package soon, but this will stay more complicated than "drag and it should have everything there".

We are open to contributions: if you want to make your own package, make a pull request and we will review it for sure :)

Mickaël
