### ISSUE TITLE
[Admin] Some Issue with Forms

### ISSUE THREAD

**Issue by quentin-boulard** [backbee/BackBee#520]
Hi, 

I try to develop a form with the Controller method createFormBuilder but I receive an error 500 with the error message :  

*ClassNotFoundException in Controller.php line 138 : 
Attempted to load class Forms from namespace Symfony\Component\Form
Did you forget a use statement for another namespace?*

It seems that the "Form" from Symfony Component is not loaded in the backbee composer.json but if I add it and update the composer,  I have exactly the same problem. 

Is this feature functional or in development  ?

Thanks.

**Comment by mickaelandrieu** [comment]
@quentin-boulard the feature is functional but need an update (Form component is now an optional dependency). 

Did you add symfony/form component in the composer.json file of your project? Also can you try to create an instance of Form object to check the availability of the classes in your project?

**Comment by ndufreche** [comment]
This issue has been fix with the PR backbee/BbCoreJs#911
