### ISSUE TITLE
Error with sqlite

### ISSUE THREAD

**Issue by pyrech** [backbee/BackBee#536]
I'm giving a try to BackBee but I'm facing an error in the web installer. After submitting the step 3 (with the sqlite driver selected). I got the following exceptions:

```
2/2 DBALException in DBALException.php line 91: An exception occurred while executing 'SELECT t0.id AS id1, t0."type" AS type2, t0."key" AS key3, t0."value" AS value4, t0."scope" AS scope5 FROM registry t0 WHERE t0."key" = ? AND t0."scope" = ? LIMIT 1' with params ["demo", "BUNDLE_CONFIG.default."]:

SQLSTATE[HY000]: General error: 1 no such table: registry

1/2 PDOException in Connection.php line 691:

SQLSTATE[HY000]: General error: 1 no such table: registry 
```

Additionally, an error is printed at the top of the page:

```
Failed to connect to database with the current exception message : Warning: mysqli_connect(): (HY000/2002): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

PHP version is 5.6.4-4ubuntu6.2 and php5-sqlite is installed.

Here is a screenshot of the problem:
![capture du 2015-08-30 22 46 19](https://cloud.githubusercontent.com/assets/2021641/9569363/f6c9067c-4f68-11e5-97ed-7d1e4a1dfd72.png)

**Comment by mickaelandrieu** [comment]
Hi @pyrech, we have removed the sqlite driver from installer (we are aware of some issues) and we will try to re-add it for 1.1.

For now,  you can use MySQL driver (you only need to create a database).

I will tag a new release to remove this option in branch 1.0.x now, thanks for the catch !

**Comment by mickaelandrieu** [comment]
Hi again @pyrech, you can use ``composer update`` command, a new release is available => https://github.com/backbee/backbee-standard/releases/tag/v1.0.2

**Comment by pyrech** [comment]
Okay, I will try it this evening. Thanks for the answer :)
