### ISSUE TITLE
$_subcontent and $_parentcontent Many To Many?

### ISSUE THREAD

**Issue by gonzalovilaseca** [backbee/BackBee#635]
Why are this relations many to many?
Shouldn't both be one to many?
Content can have multiple subcontents, but a subcontents can only belong to a parent content (for what I've seen implemented in BB).
Every time you drop a block a new instance is created and saved in DB.

**Comment by crouillon** [comment]
Hi @gonzalovilaseca, a content can be shared on several pages: in a contentset drop zone you can either create a new block content or add an already existing one by the content selector feature.

**Comment by gonzalovilaseca** [comment]
oh, ok I see, hadn't seen that feature. Thxs.
