### ISSUE TITLE
Subdirectory Installation of BackBee

### ISSUE THREAD

**Issue by GaneshKandu** [backbee/BackBee#640]
Hi, Is Possible to install BackBee in Sub directory because I have Installed BackBee in Sun directory and getting error in browsers network
<pre style="color:#FF0000">
"NetworkError: 404 Not Found - http://127.0.0.1/resources/css/bootstrap.min.css"
"NetworkError: 404 Not Found - http://127.0.0.1/resources/css/font-awesome.min.css"
"NetworkError: 404 Not Found - http://127.0.0.1/resources/css/magnific-popup.css"
"NetworkError: 404 Not Found - http://127.0.0.1/resources/css/jquery.bxslider.css"
"NetworkError: 404 Not Found - http://127.0.0.1/resources/css/elementTransitions.css"
"NetworkError: 404 Not Found - http://127.0.0.1/resources/css/menu-mobile.css"
"NetworkError: 404 Not Found - http://127.0.0.1/resources/css/transition.css"
"NetworkError: 404 Not Found - http://127.0.0.1/resources/js/modernizr.custom.min.js"
"NetworkError: 404 Not Found - http://127.0.0.1/resources/toolbar/dist/css/bb-ui-login.min.css"
"NetworkError: 404 Not Found - http://127.0.0.1/resources/toolbar/dist/require.js"
"NetworkError: 404 Not Found - http://127.0.0.1/resources/js/ellipsis.js"
"NetworkError: 404 Not Found - http://127.0.0.1/resources/css/inprogress-wm.css"
"NetworkError: 404 Not Found - http://127.0.0.1/resources/css/inprogress.css"
"NetworkError: 404 Not Found - http://127.0.0.1/resources/toolbar/dist/css/bb-ui-login.min.css"
"NetworkError: 404 Not Found - http://127.0.0.1/resources/toolbar/dist/require.js"
"NetworkError: 404 Not Found - http://127.0.0.1/resources/js/ellipsis.js"
</pre>

**Comment by eric-chau** [comment]
Hi @GaneshKandu, can you give me more details about your installation please?

**Comment by GaneshKandu** [comment]
in root it seens like script looking  resources directory for js and css but i dont have any resources directory in root

**Comment by eric-chau** [comment]
Ok. Do you setup a virtualhost? Cause BackBee use of URL rewriting to do so.

**Comment by GaneshKandu** [comment]
no

**Comment by eric-chau** [comment]
Ok, that's why you get this issue. Did you follow the web installation? The last step of the installation propose you to copy and setup the virtualhost (for apache2 and nginx).

**Comment by GaneshKandu** [comment]
if i want to install using any ip not a localhost or any loopback address then how i can do that??
because i cant access my domain with loopbacks address if its hosting or remote server

**Comment by eric-chau** [comment]
Ok you can do it from the loopback address or any IP. But to run the install you have to modify the ``public/install.php`` first by commenting this part of the script:

```php
/* if (!in_array(@$_SERVER['REMOTE_ADDR'], [
    '127.0.0.1',
    '10.0.2.2',
    '::1',
])) {
    header('HTTP/1.0 403 Forbidden');
    exit('This script is only accessible from localhost.');
} */
```

Admitting that your IP is ``127.0.0.1``, to install BackBee you have to access to ``http://127.0.0.1/public/install.php``. If you can't or don't want to setup a virtualhost, you can access to your newly installed site by accessing to ``http://127.0.0.1/public/``.

Note that using a virtualhost with speed up alot your website.

Hope it helps you.

**Comment by GaneshKandu** [comment]
Thax, Its working

**Comment by stevecheung12** [comment]
Please help, I have an issue with nginx redirection after installation. When I opened the page, the welcoming page pointed to public/resources instead of redirect to repository/Resources/...
my nginx configuration:
server {
    listen 443;

    server_name backbee;
    root /var/www/backbee/public/;

    error_log /var/log/nginx/backbee.error.log;
    access_log /var/log/nginx/backbee.access.log;

        ssl_certificate /etc/ssl/certs/backbee.crt;
        ssl_certificate_key /etc/ssl/private/backbee.key;

    location ~ /resources/toolbar/(.*) {
        alias /var/www/backbee/;
        try_files /repository/Resources/$1 /vendor/backbee/bb-core-js/$1 @rewriteapp;
    }

    location ~ /resources/(.*) {
        alias /var/www/backbee/;
        try_files /repository/Resources/$1 /vendor/backbee/backbee/Resources/$1 @rewriteapp;
    }

    location ~ /images/([a-f0-9]+)/([a-f0-9]+)/(.+)\.([^\.]+) {
        alias /var/www/backbee/;
        try_files /repository/Data/Storage/$1/$2.$4 /repository/Data/Media/$1/$2.$4 @rewriteapp;
    }


    location @emptygif404 { empty_gif; }

    location / {
        try_files $uri @rewriteapp;
