### ISSUE TITLE
[RFC] Introduced the BackBee i18 manager

### ISSUE THREAD

**Issue by mickaelandrieu** [backbee/BackBee#652]
Translations can be hard to manage.

As BackBee actualy handle 6 or 7 languages, we can't ask any contributor to check for each missing key for each language, or to deal with json.

This is why I suggest to make official a website to help internal and external people to contribute to translations.

This website should be open, open source and free, it shoud be able to point missing key for each language and create corresponding file for each update.

Also, it should be able to self update when new translatation is done on the repository.

**Demo**
![demo](https://cloud.githubusercontent.com/assets/1247388/12717270/1a931226-c8e7-11e5-8658-13a091628aa0.png)

**Missing keys**
![missing_keys](https://cloud.githubusercontent.com/assets/1247388/12717271/1aa6a5d4-c8e7-11e5-9025-78d4761731ef.png)

**Validation & Download**
![validate_and_download](https://cloud.githubusercontent.com/assets/1247388/12717272/1aa98632-c8e7-11e5-9765-25b02ae2d0a5.png)

Can you create a new repository and give me rights to work on it ?

**Comment by eric-chau** [comment]
Okay @mickaelandrieu, thank you for your futures contributions =) ping @crouillon to validate it.

**Comment by crouillon** [comment]
:+1: thanks @mickaelandrieu

**Comment by mickaelandrieu** [comment]
@crouillon I need a new repository in order to push the web application ;)

**Comment by mickaelandrieu** [comment]
ping @crouillon @eric-chau  :p http://translator.mickael-andrieu.fr/
