### ISSUE TITLE
Slowness of contents saving

### ISSUE THREAD

**Issue by mickaelandrieu** [backbee/BackBee#8]
When contributing a complex page (number of contents, depth / level of contents, etc ...) It can easely happen that Backbee will say he has more than 50 contents to save.

The problem is that the save operation takes forever, and it even looks like the duration is exponential but that's more of a feeling....

For instance my last save operation was 109 contents (still don't really get this number since I definitly don't have 109 contents on my page even including containers ... but let say that Bakbee know better than me)... It took almost 3min to save on my local computer (Linux + SSD) knowing that usually my local computer is twice ou three times faster than preprods/prods.....

That's not a bug, the saving works at the end, but definitly something that should be taken care of.

* First it doesn't seem normal at all that it takes so long to store contents and probably there's some bottleneck/missing index or so somewhere
* and Second we're going straight into problems regarding the complexity of pages that Backbee is capable to handle while offering  a reasonnably confortable contribution.
* On some slow preprods/prods I think it can even take around 8/10 minutes with more than 100 contents.... Didn't have the time to make real tests though !

**Comment by eric-chau** [comment]
Out of date issue.
