### ISSUE TITLE
[Insight] Source code should not contain TODO comments - in Renderer/Adapter/Twig.php, line 157

### ISSUE THREAD

**Issue by mickaelandrieu** [backbee/BackBee#97]
**[in Renderer/Adapter/Twig.php, line 157](https://github.com/backbee/BackBee/blob/master/Renderer/Adapter/Twig.php#L157)**

> TODO comments are left in the code when a feature (or a bug) isn't completely developed (or fixed). You should complete the implementation and remove the comment.

```php
        if ((count($paths) !== count($templateDir)) || (0 < count(array_diff($paths, $templateDir)))) {
            $this->loader->removeAllPaths();
            try {
                $this->loader->setPaths($templateDir);
            } catch (\Twig_Error_Loader $e) {
                //@Todo what to do when one of path does not exist
            }
        }
    }

    /**
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/c9dd6e24-288f-41a9-8400-82e5fae6015b/analyses/57)_

**Comment by eric-chau** [comment]
This issue is out of date.
